# Generated by Django 6.0.1 on 2026-01-18 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVA', 'Administrativa'), ('ENSINO', 'Ensino'), ('CORREICIONAL', 'Correicional'), ('COMISSAO', 'Comissão'), ('ACAO_SOCIAL', 'Ação Social')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Missão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20, verbose_name='Status')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento de Referência (SEI/BG)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG Militar')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('nome_guerra', models.CharField(blank=True, max_length=50, verbose_name='Nome de Guerra')),
                ('posto', models.CharField(choices=[('Cel', 'Coronel'), ('Ten Cel', 'Tenente-Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1º Ten', 'Primeiro-Tenente'), ('2º Ten', 'Segundo-Tenente'), ('Asp', 'Aspirante')], max_length=20, verbose_name='Posto')),
                ('quadro', models.CharField(choices=[('QOBM', 'Quadro de Oficiais BM'), ('QOS', 'Quadro de Oficiais de Saúde'), ('QOBM/Comb.', 'QOBM/Combatente'), ('QOBM/Intd.', 'QOBM/Intendente'), ('QOBM/Mnt.', 'QOBM/Manutenção'), ('QOBM/Mus.', 'QOBM/Músico')], max_length=20, verbose_name='Quadro')),
                ('obm', models.CharField(blank=True, max_length=100, verbose_name='OBM de Lotação')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='Função')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_oficiais/', verbose_name='Foto')),
                ('score', models.FloatField(default=0.0, verbose_name='Score de Carga')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Oficial',
                'verbose_name_plural': 'Oficiais',
                'ordering': ['posto', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('comandante', 'Comandante de Unidade'), ('oficial', 'Oficial')], default='oficial', max_length=20, verbose_name='Perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('oficial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='missoes.oficial', verbose_name='Oficial Vinculado')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDesignacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_missao', models.CharField(max_length=200, verbose_name='Nome da Missão')),
                ('funcao_na_missao', models.CharField(max_length=100, verbose_name='Função na Missão')),
                ('complexidade', models.CharField(max_length=20, verbose_name='Complexidade')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Nº SEI / BG')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('observacao_avaliador', models.TextField(blank=True, verbose_name='Observação do Avaliador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='missoes.oficial', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Designação',
                'verbose_name_plural': 'Solicitações de Designação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, verbose_name='Sigla')),
                ('tipo', models.CharField(choices=[('COMANDO_GERAL', 'Comando Geral'), ('DIRETORIA', 'Diretoria'), ('BBM', 'Batalhão BM'), ('CIBM', 'Companhia Independente BM'), ('CBM', 'Companhia BM'), ('SECAO', 'Seção')], max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('comando_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinadas', to='missoes.unidade', verbose_name='Comando Superior')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Designacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_na_missao', models.CharField(choices=[('COMANDANTE', 'Comandante'), ('SUBCOMANDANTE', 'Subcomandante'), ('COORDENADOR', 'Coordenador'), ('PRESIDENTE', 'Presidente'), ('MEMBRO', 'Membro'), ('AUXILIAR', 'Auxiliar'), ('INSTRUTOR', 'Instrutor'), ('ENCARREGADO', 'Encarregado'), ('RELATOR', 'Relator'), ('ESCRIVAO', 'Escrivão')], default='MEMBRO', max_length=20, verbose_name='Função na Missão')),
                ('complexidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Complexidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='APROVADA', max_length=20, verbose_name='Status da Designação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designacoes', to='missoes.missao', verbose_name='Missão')),
                ('oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designacoes', to='missoes.oficial', verbose_name='Oficial')),
            ],
            options={
                'verbose_name': 'Designação',
                'verbose_name_plural': 'Designações',
                'ordering': ['-criado_em'],
                'unique_together': {('missao', 'oficial')},
            },
        ),
    ]
