# Generated by Django 6.0.1 on 2026-01-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='quadro',
            field=models.CharField(choices=[('QOC', 'QOC'), ('QOA/Adm', 'QOA/Adm'), ('QOA/Mús', 'QOA/Mús'), ('QOM/Médico', 'QOM/Médico'), ('QOM/Dentista', 'QOM/Dentista')], max_length=20, verbose_name='Quadro'),
        ),
    ]
