# Generated by Django 6.0.1 on 2026-01-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0003_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='data_fim_missao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='data_inicio_missao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='descricao_missao',
            field=models.TextField(blank=True, verbose_name='Descrição da Missão'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='designacao_criada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='missoes.designacao', verbose_name='Designação Criada'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='local_missao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='missao_existente',
            field=models.ForeignKey(blank=True, help_text='Se a missão já existe, selecione aqui', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='missoes.missao', verbose_name='Missão Existente'),
        ),
        migrations.AddField(
            model_name='solicitacaodesignacao',
            name='tipo_missao',
            field=models.CharField(blank=True, choices=[('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVA', 'Administrativa'), ('ENSINO', 'Ensino'), ('CORREICIONAL', 'Correicional'), ('COMISSAO', 'Comissão'), ('ACAO_SOCIAL', 'Ação Social')], max_length=20, verbose_name='Tipo da Missão'),
        ),
        migrations.AlterField(
            model_name='solicitacaodesignacao',
            name='complexidade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20, verbose_name='Complexidade'),
        ),
        migrations.AlterField(
            model_name='solicitacaodesignacao',
            name='funcao_na_missao',
            field=models.CharField(choices=[('COMANDANTE', 'Comandante'), ('SUBCOMANDANTE', 'Subcomandante'), ('COORDENADOR', 'Coordenador'), ('PRESIDENTE', 'Presidente'), ('MEMBRO', 'Membro'), ('AUXILIAR', 'Auxiliar'), ('INSTRUTOR', 'Instrutor'), ('ENCARREGADO', 'Encarregado'), ('RELATOR', 'Relator'), ('ESCRIVAO', 'Escrivão')], default='MEMBRO', max_length=20, verbose_name='Função na Missão'),
        ),
        migrations.AlterField(
            model_name='solicitacaodesignacao',
            name='nome_missao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da Missão'),
        ),
        migrations.AddIndex(
            model_name='designacao',
            index=models.Index(fields=['missao', 'oficial'], name='missoes_des_missao__85fcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='designacao',
            index=models.Index(fields=['criado_em'], name='missoes_des_criado__0abc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='designacao',
            index=models.Index(fields=['complexidade'], name='missoes_des_complex_d9bb68_idx'),
        ),
        migrations.AddIndex(
            model_name='designacao',
            index=models.Index(fields=['funcao_na_missao'], name='missoes_des_funcao__eed00a_idx'),
        ),
        migrations.AddIndex(
            model_name='designacao',
            index=models.Index(fields=['status'], name='missoes_des_status_a3e651_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['tipo'], name='missoes_mis_tipo_60d790_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['status'], name='missoes_mis_status_f50391_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['data_inicio'], name='missoes_mis_data_in_6ade96_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['criado_em'], name='missoes_mis_criado__b76ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaodesignacao',
            index=models.Index(fields=['status'], name='missoes_sol_status_2578a5_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaodesignacao',
            index=models.Index(fields=['criado_em'], name='missoes_sol_criado__1062d0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaodesignacao',
            index=models.Index(fields=['solicitante'], name='missoes_sol_solicit_992d18_idx'),
        ),
    ]
