# Generated by Django 6.0.1 on 2026-01-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0002_alter_oficial_quadro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('corregedor', 'Corregedor'), ('bm3', 'BM/3'), ('comando_geral', 'Comando-Geral'), ('comandante', 'Comandante'), ('oficial', 'Oficial')], default='oficial', max_length=20, verbose_name='Perfil'),
        ),
    ]
