# Generated by Django 6.0.1 on 2026-01-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0004_solicitacaodesignacao_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficial',
            name='score',
        ),
    ]
