# Generated by Django 6.0.1 on 2026-01-30 13:56
# Modified to be compatible with fresh databases (no legacy tables)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0007_create_solicitacao'),
    ]

    operations = [
        # Índices de SolicitacaoDesignacao já foram removidos com DROP TABLE IF EXISTS na 0006
        # Não precisamos fazer nada aqui

        # RemoveIndex para designacao, missao e solicitacao usando SQL seguro
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS missoes_des_missao__85fcfd_idx;
                DROP INDEX IF EXISTS missoes_des_criado__0abc5f_idx;
                DROP INDEX IF EXISTS missoes_des_complex_d9bb68_idx;
                DROP INDEX IF EXISTS missoes_des_funcao__eed00a_idx;
                DROP INDEX IF EXISTS missoes_des_status_a3e651_idx;
                DROP INDEX IF EXISTS missoes_mis_tipo_60d790_idx;
                DROP INDEX IF EXISTS missoes_mis_status_f50391_idx;
                DROP INDEX IF EXISTS missoes_mis_data_in_6ade96_idx;
                DROP INDEX IF EXISTS missoes_mis_criado__b76ac5_idx;
                DROP INDEX IF EXISTS missoes_sol_status_unif_idx;
                DROP INDEX IF EXISTS missoes_sol_criado_unif_idx;
                DROP INDEX IF EXISTS missoes_sol_solicit_unif_idx;
                DROP INDEX IF EXISTS missoes_sol_tipo_idx;
                DROP INDEX IF EXISTS missoes_sol_status_2578a5_idx;
                DROP INDEX IF EXISTS missoes_sol_criado__1062d0_idx;
                DROP INDEX IF EXISTS missoes_sol_solicit_992d18_idx;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='oficial',
            name='posto',
            field=models.CharField(choices=[('Cel', 'Coronel'), ('TC', 'Tenente-Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1º Ten', 'Primeiro-Tenente'), ('2º Ten', 'Segundo-Tenente'), ('Asp', 'Aspirante')], max_length=20, verbose_name='Posto'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status_missao',
            field=models.CharField(blank=True, choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status da Missão'),
        ),
        # Deletar SolicitacaoDesignacao do estado das migrações
        # A tabela já foi deletada anteriormente, então usamos SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SolicitacaoDesignacao',
                ),
            ],
            database_operations=[
                # Tabela já foi deletada, não fazer nada no banco
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS missoes_solicitacaodesignacao CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
