# Generated by Django 6.0.1 on 2026-01-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0016_alter_designacao_funcao_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='complexidade',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='funcao_na_missao',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='dec',
            field=models.IntegerField(blank=True, help_text='Preenchido pelo avaliador na aprovação', null=True, verbose_name='DEC'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='funcao_criada',
            field=models.ForeignKey(blank=True, help_text='Preenchido automaticamente na aprovação se tipo=NOVA_MISSAO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem_funcao', to='missoes.funcao', verbose_name='Função Criada'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='funcao_existente',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas se tipo=DESIGNACAO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_designacao', to='missoes.funcao', verbose_name='Função Existente'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='grs',
            field=models.IntegerField(blank=True, help_text='Preenchido pelo avaliador na aprovação', null=True, verbose_name='GRS'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nome_funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Função'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nqt',
            field=models.IntegerField(blank=True, help_text='Preenchido pelo avaliador na aprovação', null=True, verbose_name='NQT'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tde',
            field=models.IntegerField(blank=True, help_text='Preenchido pelo avaliador na aprovação', null=True, verbose_name='TDE'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('COMANDO_GERAL', 'Comando-Geral'), ('ORGAO_DIRECAO', 'Órgão de Direção'), ('ORGAO_APOIO', 'Órgão de Apoio'), ('ORGAO_EXEC', 'Órgão de Execução'), ('SECAO_EMG', 'Seção do EMG'), ('BBM', 'Batalhão BM'), ('CIBM', 'Cia Independente BM'), ('PBM', 'Pelotão BM'), ('DBM', 'Destacamento BM')], max_length=20, verbose_name='Tipo'),
        ),
    ]
