# Generated by Django 6.0.1 on 2026-02-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0019_normalize_missao_local_choices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solicitacaodesignacao',
            name='missoes_sol_status_2578a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacaodesignacao',
            name='missoes_sol_criado__1062d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacaodesignacao',
            name='missoes_sol_solicit_992d18_idx',
        ),
        migrations.RemoveIndex(
            model_name='designacao',
            name='missoes_des_missao__85fcfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='designacao',
            name='missoes_des_criado__0abc5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='designacao',
            name='missoes_des_complex_d9bb68_idx',
        ),
        migrations.RemoveIndex(
            model_name='designacao',
            name='missoes_des_funcao__eed00a_idx',
        ),
        migrations.RemoveIndex(
            model_name='designacao',
            name='missoes_des_status_a3e651_idx',
        ),
        migrations.RemoveIndex(
            model_name='missao',
            name='missoes_mis_tipo_60d790_idx',
        ),
        migrations.RemoveIndex(
            model_name='missao',
            name='missoes_mis_status_f50391_idx',
        ),
        migrations.RemoveIndex(
            model_name='missao',
            name='missoes_mis_data_in_6ade96_idx',
        ),
        migrations.RemoveIndex(
            model_name='missao',
            name='missoes_mis_criado__b76ac5_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='missoes_sol_status_unif_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='missoes_sol_criado_unif_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='missoes_sol_solicit_unif_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='missoes_sol_tipo_idx',
        ),
        migrations.DeleteModel(
            name='SolicitacaoDesignacao',
        ),
    ]
