# Generated by Django 6.0.1 on 2026-02-04 03:35
# Modified: operações já foram tratadas na migration 0008

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0019_normalize_missao_local_choices'),
    ]

    # Todas as operações já foram executadas na migration 0008
    # Esta migration é mantida apenas para preservar o histórico
    operations = []
