# Generated by Django 6.0.1 on 2026-02-05 21:08
# Modified: operações de índices e SolicitacaoDesignacao já foram tratadas em migrações anteriores

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0021_missao_finalizacao_and_status_auto'),
    ]

    # Apenas atualiza o campo status_missao em Solicitacao
    # As outras operações (RemoveIndex e DeleteModel) já foram executadas anteriormente
    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status_missao',
            field=models.CharField(blank=True, choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('ATRASADA', 'Atrasada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('SUSPENSA', 'Suspensa')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status da Missão'),
        ),
    ]
