# Generated by Django 6.0.1 on 2026-02-05 21:13
# Modified to handle potentially missing indices safely

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0022_remove_solicitacaodesignacao_missoes_sol_status_2578a5_idx_and_more'),
    ]

    operations = [
        # Drop indices safely using IF EXISTS
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='designacao',
                    name='missoes_des_missao__85fcfd_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_des_missao__85fcfd_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='designacao',
                    name='missoes_des_criado__0abc5f_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_des_criado__0abc5f_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='designacao',
                    name='missoes_des_complex_d9bb68_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_des_complex_d9bb68_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='designacao',
                    name='missoes_des_funcao__eed00a_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_des_funcao__eed00a_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='designacao',
                    name='missoes_des_status_a3e651_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_des_status_a3e651_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='missao',
                    name='missoes_mis_tipo_60d790_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_mis_tipo_60d790_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='missao',
                    name='missoes_mis_status_f50391_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_mis_status_f50391_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='missao',
                    name='missoes_mis_data_in_6ade96_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_mis_data_in_6ade96_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='missao',
                    name='missoes_mis_criado__b76ac5_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_mis_criado__b76ac5_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='solicitacao',
                    name='missoes_sol_status_unif_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_sol_status_unif_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='solicitacao',
                    name='missoes_sol_criado_unif_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_sol_criado_unif_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='solicitacao',
                    name='missoes_sol_solicit_unif_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_sol_solicit_unif_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='solicitacao',
                    name='missoes_sol_tipo_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "missoes_sol_tipo_idx";',
                    reverse_sql='SELECT 1;'
                ),
            ],
        ),
    ]
