# Generated by Django 6.0.1 on 2026-02-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0023_remove_designacao_missoes_des_missao__85fcfd_idx_and_more'),
        ('missoes', '0023_solicitacao_prorrogacao_prazo'),
    ]

    operations = [
    ]
