# Generated by Django 6.0.1 on 2026-02-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0025_designacao_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEstruturaMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('sigla', models.CharField(blank=True, help_text='Ex: PAD, IPM, CEBM', max_length=20, verbose_name='Sigla')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVA', 'Administrativa'), ('ENSINO', 'Ensino'), ('CORREICIONAL', 'Correicional'), ('COMISSAO', 'Comissão'), ('ACAO_SOCIAL', 'Ação Social')], max_length=20, verbose_name='Tipo Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Missão',
                'verbose_name_plural': 'Templates de Missões',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='missao',
            name='numero',
            field=models.CharField(blank=True, help_text='Ex: 001/2026 (para PADs, IPMs, etc.)', max_length=50, verbose_name='Número/Identificador'),
        ),
        migrations.AddField(
            model_name='missao',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, as funções podem ser herdadas do template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='missoes.templateestruturamissao', verbose_name='Template Base'),
        ),
        migrations.CreateModel(
            name='TemplateFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Função')),
                ('tde', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], default=2, verbose_name='TDE (Tempo de Dedicação Exigido)')),
                ('nqt', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], default=2, verbose_name='NQT (Nível de Qualificação Técnica)')),
                ('grs', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], default=2, verbose_name='GRS (Grau de Responsabilidade)')),
                ('dec', models.IntegerField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')], default=1, verbose_name='DEC (Dimensão do Efetivo Comandado)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('template_missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_template', to='missoes.templateestruturamissao', verbose_name='Template de Missão')),
            ],
            options={
                'verbose_name': 'Template de Função',
                'verbose_name_plural': 'Templates de Funções',
                'ordering': ['template_missao__nome', 'nome'],
                'unique_together': {('template_missao', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcao',
            name='template_funcao',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, os critérios foram herdados deste template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='missoes.templatefuncao', verbose_name='Template de Origem'),
        ),
    ]
