# Generated by Django 6.0.1 on 2026-02-09 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0026_add_template_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='numero_missao',
            field=models.CharField(blank=True, help_text='Ex: 001/2026 - usado apenas com template', max_length=50, verbose_name='Número/Identificador da Missão'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='template_funcao',
            field=models.ForeignKey(blank=True, help_text='Função do template que o solicitante ocupará', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='missoes.templatefuncao', verbose_name='Função do Template'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='template_missao',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, a missão será criada a partir deste template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='missoes.templateestruturamissao', verbose_name='Template de Missão'),
        ),
    ]
